### ISSUE TITLE
[bug] 给初始值渲染有 bug

### ISSUE THREAD

**Issue by zhangshichuan** [Wayne-007/react-weektime-picker#7]
![image](https://user-images.githubusercontent.com/8280832/116353308-1c7cd280-a829-11eb-8372-30b89212e72e.png)
通过 外层组件给 传入一个已有的 value. 最下面全部显示 undefined

**Comment by wenson** [comment]
这个问题 修复了吗？

**Comment by wenson** [comment]
> ![image](https://user-images.githubusercontent.com/8280832/116353308-1c7cd280-a829-11eb-8372-30b89212e72e.png)
> 通过 外层组件给 传入一个已有的 value. 最下面全部显示 undefined

修复了吗 ?
